### ISSUE TITLE
I have an issue running nmake in VS2015 x86 Native Command Prompt.

### ISSUE THREAD

**Issue by GroundenseAndWings** [P0L3NARUBA/roblox-hitius-sourcecode#1]
when I run nmake, I keep getting errors for "illegal character {" when I ran the command in the VS2015 thing. how do I fix the illegal character errors?

**Comment by WH0LEWHALE** [comment]
Issue about QT?

**Comment by GroundenseAndWings** [comment]
yea it was QT, I got it now though, I'm gonna close this issue.
