### ISSUE TITLE
When I try building the RobloxStudio project in Visual Studio 2019, I get this error.

### ISSUE THREAD

**Issue by GroundenseAndWings** [P0L3NARUBA/roblox-hitius-sourcecode#2]
After building boost and Qt, I go into the sln, and build RobloxStudio only, I get this error:

Cannot open include file: 'Security/RandomConstant.h': No such file or directory

**Comment by WH0LEWHALE** [comment]
Just check your includes because the file is not missing.

**Comment by WH0LEWHALE** [comment]
Download this: https://github.com/ui0ppk/roblox-master-unmodified/blob/master/App%2Finclude%2Fsecurity%2FRandomConstant.h

And put that to App/include/security
